# Generated by Django 6.0.2 on 2026-02-24 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('locality', models.CharField(blank=True, db_index=True, max_length=150)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=7)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
            ],
            options={
                'ordering': ['country', 'state', 'city', 'locality'],
                'indexes': [models.Index(fields=['city', 'state'], name='core_locati_city_ef2718_idx'), models.Index(fields=['country'], name='core_locati_country_eabc72_idx'), models.Index(fields=['pincode'], name='core_locati_pincode_0bc106_idx')],
            },
        ),
    ]
