# Generated by Django 6.0.2 on 2026-02-24 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_type', models.CharField(choices=[('PROPERTY_APPROVED', 'Property Approved'), ('PROPERTY_REJECTED', 'Property Rejected'), ('NEW_CONTACT', 'New Contact'), ('NEW_FAVORITE', 'New Favorite'), ('NEW_MESSAGE', 'New Message'), ('SYSTEM', 'System')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
