PROPERTY_STATUS_DRAFT = "DRAFT"
PROPERTY_STATUS_PENDING = "PENDING"
PROPERTY_STATUS_ACTIVE = "ACTIVE"
PROPERTY_STATUS_RENTED = "RENTED"
PROPERTY_STATUS_EXPIRED = "EXPIRED"
PROPERTY_STATUS_REJECTED = "REJECTED"

OWNER_ROLE = "OWNER"
TENANT_ROLE = "TENANT"

NOTIFICATION_PROPERTY_APPROVED = "PROPERTY_APPROVED"
NOTIFICATION_PROPERTY_REJECTED = "PROPERTY_REJECTED"
NOTIFICATION_NEW_CONTACT = "NEW_CONTACT"
NOTIFICATION_NEW_FAVORITE = "NEW_FAVORITE"
NOTIFICATION_NEW_MESSAGE = "NEW_MESSAGE"
NOTIFICATION_SYSTEM = "SYSTEM"

CONVERSATION_STATUS_ACTIVE = "ACTIVE"
CONVERSATION_STATUS_ARCHIVED = "ARCHIVED"

MESSAGE_TYPE_TEXT = "TEXT"
MESSAGE_TYPE_IMAGE = "IMAGE"
MESSAGE_TYPE_SYSTEM = "SYSTEM"
