# Generated by Django 6.0.2 on 2026-02-24 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='properties.property'),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contactlog',
            index=models.Index(fields=['property', 'tenant'], name='contacts_co_propert_37c9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlog',
            index=models.Index(fields=['owner'], name='contacts_co_owner_i_8a1e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlog',
            index=models.Index(fields=['created_at'], name='contacts_co_created_469110_idx'),
        ),
    ]
