# Generated by Django 6.0.2 on 2026-02-24 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('properties', '0003_property_area_sqft_property_bathrooms_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location'], name='properties__locatio_c0eebe_idx'),
        ),
    ]
