# Generated by Django 6.0.2 on 2026-02-24 06:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_properties__locatio_c0eebe_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='id',
            field=models.UUIDField(default=core.models.BaseModel._uuid_seq, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=core.models.BaseModel._uuid_seq, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='id',
            field=models.UUIDField(default=core.models.BaseModel._uuid_seq, editable=False, primary_key=True, serialize=False),
        ),
    ]
