# Generated by Django 6.0.2 on 2026-03-02 04:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_location_id'),
        ('properties', '0005_alter_amenity_id_alter_property_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'created_at'], name='properties__status_8e4eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['total_views'], name='properties__total_v_51051d_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['total_favorites'], name='properties__total_f_3f1e47_idx'),
        ),
    ]
