# Generated by Django 6.0.2 on 2026-06-09 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0004_message_client_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="message",
            name="message_content_or_image_required",
        ),
        migrations.AddField(
            model_name="message",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to="communication/messages/audio/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="communication/messages/images/"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("IMAGE", "Image"),
                    ("SYSTEM", "System"),
                    ("AUDIO", "Audio"),
                ],
                db_index=True,
                default="TEXT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content__gt", ""),
                    ("image__isnull", False),
                    ("audio__isnull", False),
                    _connector="OR",
                ),
                name="message_content_or_image_or_audio_required",
            ),
        ),
    ]
