# Generated by Django 6.0.2 on 2026-06-09 06:10

import apps.communication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "communication",
            "0005_remove_message_message_content_or_image_required_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.communication.models.select_audio_storage,
                upload_to="communication/messages/audio/",
            ),
        ),
    ]
