# Generated by Django 6.0.2 on 2026-02-24 06:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=core.models.BaseModel._uuid_seq, editable=False, primary_key=True, serialize=False),
        ),
    ]
